### ISSUE TITLE
Interface Designer -> Qt5 Tasarimci Cökme Hatasi

### ISSUE THREAD

**Issue by jolyjokerz** [pisilinux/PisiLinux#797]
```
Application: designer (designer), signal: Segmentation fault
[KCrash Handler]
#5  0x00007fbc4796fb86 in ?? () from /usr/lib/libKF5KIOFileWidgets.so.5
#6  0x00007fbc47973ed0 in ?? () from /usr/lib/libKF5KIOFileWidgets.so.5
#7  0x00007fbc57ee84be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#8  0x00007fbc59129d9f in QActionGroup::triggered(QAction*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007fbc5912aaf9 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007fbc57ee84be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#11 0x00007fbc59126a42 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007fbc59128e68 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007fbc592a2c3a in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007fbc592a8d64 in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007fbc592acf16 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007fbc59171048 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007fbc592ad933 in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007fbc5913035c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007fbc59135c18 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007fbc57eba8a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#21 0x00007fbc59134942 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007fbc5918b71f in ?? () from /usr/lib/libQt5Widgets.so.5
#23 0x00007fbc5918dcfb in ?? () from /usr/lib/libQt5Widgets.so.5
#24 0x00007fbc5913035c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007fbc591354e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#26 0x00007fbc57eba8a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x00007fbc5898d27d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#28 0x00007fbc5898ec55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#29 0x00007fbc58973e5f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#30 0x00007fbc4f7c12c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#31 0x00007fbc56b2af1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007fbc56b2b1c8 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007fbc56b2b26c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007fbc57f0fb97 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007fbc57eb8262 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007fbc592a7b50 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/libQt5Widgets.so.5
#37 0x00007fbc47931b49 in KDirOperator::activatedMenu(KFileItem const&, QPoint const&) () from /usr/lib/libKF5KIOFileWidgets.so.5
#38 0x00007fbc4792dcc5 in KDirOperator::Private::_k_openContextMenu(QPoint const&) () from /usr/lib/libKF5KIOFileWidgets.so.5
#39 0x00007fbc4793523d in ?? () from /usr/lib/libKF5KIOFileWidgets.so.5
#40 0x00007fbc57ee84be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#41 0x00007fbc591594b5 in QWidget::customContextMenuRequested(QPoint const&) () from /usr/lib/libQt5Widgets.so.5
#42 0x00007fbc59171dbd in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007fbc5926bebe in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#44 0x00007fbc593894cb in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#45 0x00007fbc57eba6d6 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#46 0x00007fbc5913033c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#47 0x00007fbc59136cd9 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#48 0x00007fbc57eba8a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#49 0x00007fbc5918bb17 in ?? () from /usr/lib/libQt5Widgets.so.5
#50 0x00007fbc5918dcfb in ?? () from /usr/lib/libQt5Widgets.so.5
#51 0x00007fbc5913035c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#52 0x00007fbc591354e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#53 0x00007fbc57eba8a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#54 0x00007fbc5898d27d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#55 0x00007fbc5898ec55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#56 0x00007fbc58973e5f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#57 0x00007fbc4f7c12c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#58 0x00007fbc56b2af1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#59 0x00007fbc56b2b1c8 in ?? () from /usr/lib/libglib-2.0.so.0
#60 0x00007fbc56b2b26c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#61 0x00007fbc57f0fb97 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#62 0x00007fbc57eb8262 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#63 0x00007fbc593223ad in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#64 0x00007fbc5932227a in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#65 0x00007fbc59334e9d in QFileDialog::getSaveFileUrl(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) () from /usr/lib/libQt5Widgets.so.5
#66 0x00007fbc59334f4e in QFileDialog::getSaveFileName(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) () from /usr/lib/libQt5Widgets.so.5
#67 0x0000000000433b5d in ?? ()
#68 0x000000000043ba72 in ?? ()
#69 0x000000000043c10b in ?? ()
#70 0x000000000043c158 in ?? ()
#71 0x00007fbc57ee84be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#72 0x00007fbc59126a42 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#73 0x00007fbc59128e68 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#74 0x00007fbc59129737 in QAction::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#75 0x00007fbc5913035c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#76 0x00007fbc591354e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#77 0x00007fbc57eba8a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#78 0x00007fbc589b53cc in QShortcutMap::dispatchEvent(QKeyEvent*) () from /usr/lib/libQt5Gui.so.5
#79 0x00007fbc589b5529 in QShortcutMap::tryShortcutEvent(QObject*, QKeyEvent*) () from /usr/lib/libQt5Gui.so.5
#80 0x00007fbc5898a101 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/libQt5Gui.so.5
#81 0x00007fbc5898ec35 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#82 0x00007fbc58973e5f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#83 0x00007fbc4f7c12c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#84 0x00007fbc56b2af1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#85 0x00007fbc56b2b1c8 in ?? () from /usr/lib/libglib-2.0.so.0
#86 0x00007fbc56b2b26c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#87 0x00007fbc57f0fb97 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#88 0x00007fbc57eb8262 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#89 0x00007fbc57ebfe8d in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#90 0x000000000041770a in ?? ()
#91 0x00007fbc575869e0 in __libc_start_main () from /lib/libc.so.6
#92 0x0000000000417799 in ?? ()
```

**Comment by ertugerata** [comment]
bu hatayı github.com/pisilinux/main altına taşır mısın?

**Comment by jolyjokerz** [comment]
tasindi @ertugerata  https://github.com/pisilinux/main/issues/961
