### ISSUE TITLE
Dolphin 

### ISSUE THREAD

**Issue by jolyjokerz** [pisilinux/PisiLinux#798]
Pisi Linux 2.0 Alfa 6'da " Sag Tik -> Create New -> Dizin " tiklandiginda
```
Application: Dolphin (dolphin), signal: Segmentation fault
[KCrash Handler]
#5  0x00007f4c387f6b86 in ?? () from /usr/lib/libKF5KIOFileWidgets.so.5
#6  0x00007f4c387faed0 in ?? () from /usr/lib/libKF5KIOFileWidgets.so.5
#7  0x00007f4c342f44be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#8  0x00007f4c35431d9f in QActionGroup::triggered(QAction*) () from /usr/lib/libQt5Widgets.so.5
#9  0x00007f4c35432af9 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007f4c342f44be in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#11 0x00007f4c3542ea42 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007f4c35430e68 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#13 0x00007f4c355aac3a in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007f4c355b0d64 in ?? () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f4c355b4f16 in QMenu::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007f4c35479048 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007f4c355b5933 in QMenu::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007f4c3543835c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#19 0x00007f4c3543dc18 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#21 0x00007f4c3543c942 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#22 0x00007f4c3549371f in ?? () from /usr/lib/libQt5Widgets.so.5
#23 0x00007f4c35495cfb in ?? () from /usr/lib/libQt5Widgets.so.5
#24 0x00007f4c3543835c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#25 0x00007f4c3543d4e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#26 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#27 0x00007f4c34c9527d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#28 0x00007f4c34c96c55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#29 0x00007f4c34c7be5f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#30 0x00007f4c25af52c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#31 0x00007f4c2ee75f1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#32 0x00007f4c2ee761c8 in ?? () from /usr/lib/libglib-2.0.so.0
#33 0x00007f4c2ee7626c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#34 0x00007f4c3431bb97 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#35 0x00007f4c342c4262 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#36 0x00007f4c355afb50 in QMenu::exec(QPoint const&, QAction*) () from /usr/lib/libQt5Widgets.so.5
#37 0x00007f4c3a2a4249 in ?? () from /usr/lib/libkdeinit5_dolphin.so
#38 0x00007f4c3a2a477f in ?? () from /usr/lib/libkdeinit5_dolphin.so
#39 0x00007f4c3a29998c in ?? () from /usr/lib/libkdeinit5_dolphin.so
#40 0x00007f4c342f3e5a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#41 0x00007f4c39c43a24 in DolphinView::requestContextMenu(QPoint const&, KFileItem const&, QUrl const&, QList<QAction*> const&) () from /usr/lib/libdolphinprivate.so.5
#42 0x00007f4c39c1c640 in DolphinView::slotViewContextMenuRequested(QPointF const&) () from /usr/lib/libdolphinprivate.so.5
#43 0x00007f4c342f3e5a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#44 0x00007f4c39c428a5 in KItemListController::viewContextMenuRequested(QPointF const&) () from /usr/lib/libdolphinprivate.so.5
#45 0x00007f4c39bd4d6b in KItemListController::mousePressEvent(QGraphicsSceneMouseEvent*, QTransform const&) () from /usr/lib/libdolphinprivate.so.5
#46 0x00007f4c39bd5924 in KItemListController::processEvent(QEvent*, QTransform const&) () from /usr/lib/libdolphinprivate.so.5
#47 0x00007f4c39be8b22 in KItemListView::event(QEvent*) () from /usr/lib/libdolphinprivate.so.5
#48 0x00007f4c3543835c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#49 0x00007f4c3543d4e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#50 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#51 0x00007f4c3574b17e in ?? () from /usr/lib/libQt5Widgets.so.5
#52 0x00007f4c3574b559 in ?? () from /usr/lib/libQt5Widgets.so.5
#53 0x00007f4c3575566a in ?? () from /usr/lib/libQt5Widgets.so.5
#54 0x00007f4c35755ab9 in QGraphicsScene::mousePressEvent(QGraphicsSceneMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#55 0x00007f4c3575e868 in QGraphicsScene::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#56 0x00007f4c3543835c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#57 0x00007f4c3543d4e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#58 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#59 0x00007f4c35778a1f in QGraphicsView::mousePressEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#60 0x00007f4c35479669 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#61 0x00007f4c35573ebe in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#62 0x00007f4c35779e73 in QGraphicsView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#63 0x00007f4c342c66d6 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#64 0x00007f4c3543833c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#65 0x00007f4c3543dc18 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#66 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#67 0x00007f4c3543c942 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
#68 0x00007f4c354939dd in ?? () from /usr/lib/libQt5Widgets.so.5
#69 0x00007f4c35495cfb in ?? () from /usr/lib/libQt5Widgets.so.5
#70 0x00007f4c3543835c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#71 0x00007f4c3543d4e0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#72 0x00007f4c342c68a3 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#73 0x00007f4c34c9527d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#74 0x00007f4c34c96c55 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
#75 0x00007f4c34c7be5f in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#76 0x00007f4c25af52c0 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#77 0x00007f4c2ee75f1d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#78 0x00007f4c2ee761c8 in ?? () from /usr/lib/libglib-2.0.so.0
#79 0x00007f4c2ee7626c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#80 0x00007f4c3431bb97 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#81 0x00007f4c342c4262 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#82 0x00007f4c342cbe8d in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#83 0x00007f4c3a2ac628 in kdemain () from /usr/lib/libkdeinit5_dolphin.so
#84 0x00007f4c39ea59e0 in __libc_start_main () from /lib/libc.so.6
#85 0x0000000000400769 in _start ()
```

**Comment by ertugerata** [comment]
Bu konuda  acik hata var.

**Comment by jolyjokerz** [comment]
tekrar kontrol ettim, göremedim?

**Comment by ertugerata** [comment]
Pisi-2.0 icin hata girisleri core ve main altina yapiliyor.
